// Demo analysis data for when no AI key is available or for demo mode
export const DEMO_ANALYSES: Record<string, object> = {
  gym_membership: {
    contractType: "gym_membership",
    title: "اشتراك نادي رياضي سنوي",
    summary: "عقد اشتراك في نادي رياضي لمدة 12 شهرًا بدفعات شهرية وتجديد تلقائي.",
    parties: [{ name: "العميل", role: "subscriber" }, { name: "نادي الفيتنس", role: "provider" }],
    startDate: "2026-08-01",
    endDate: "2027-07-31",
    duration: "12 أشهر",
    totalCost: 2400,
    currency: "SAR",
    monthlyPayment: 200,
    annualPayment: 2400,
    deposit: 200,
    automaticRenewal: true,
    renewalNoticeDays: 30,
    cancellationAllowed: true,
    cancellationNoticeDays: 30,
    earlyCancellationPenalty: 500,
    refundPolicy: "لا يوجد استرجاع بعد بداية الاشتراك",
    trialPeriodDays: 7,
    clarityScore: 62,
    clarityExplanation: "بنود الإلغاء موزعة على عدة أقسام، وبعض الرسوم الإضافية غير موضحة بشكل كافٍ.",
    confidence: 0.91,
    clauses: [
      { category: "renewal", title: "التجديد التلقائي", simpleExplanation: "يتجدد الاشتراك تلقائيًا ما لم يتم الإلغاء قبل 30 يومًا من تاريخ الانتهاء.", riskLevel: "high", sourcePage: 4, sourceText: "يتجدد الاشتراك تلقائيًا لفترة مماثلة..." },
      { category: "cancellation", title: "غرامة الإلغاء المبكر", simpleExplanation: "في حال الإلغاء قبل انتهاء المدة تُفرض غرامة قدرها 500 ريال.", riskLevel: "high", sourcePage: 6, sourceText: "عند الإلغاء المبكر تُطبق غرامة مالية..." },
      { category: "payment", title: "موعد الدفع الشهري", simpleExplanation: "يستحق الدفع في اليوم الأول من كل شهر.", riskLevel: "low", sourcePage: 2, sourceText: "تستحق الدفعة الشهرية في مطلع كل شهر..." },
      { category: "privacy", title: "مشاركة البيانات", simpleExplanation: "قد يتم مشاركة بياناتك مع شركاء النادي لأغراض تسويقية.", riskLevel: "medium", sourcePage: 8, sourceText: "يحق للنادي مشاركة معلومات الأعضاء مع الشركاء..." },
    ],
    financialDetails: [
      { type: "monthly_payment", amount: 200, currency: "SAR", description: "الدفعة الشهرية", sourcePage: 2 },
      { type: "deposit", amount: 200, currency: "SAR", description: "رسوم التسجيل", sourcePage: 1 },
      { type: "cancellation_penalty", amount: 500, currency: "SAR", description: "غرامة الإلغاء المبكر", sourcePage: 6 },
    ],
    contractDates: [
      { type: "start", date: "2026-08-01", description: "تاريخ بداية الاشتراك" },
      { type: "end", date: "2027-07-31", description: "تاريخ انتهاء الاشتراك" },
      { type: "renewal", date: "2027-07-01", description: "آخر موعد للإلغاء قبل التجديد" },
    ],
    suggestedQuestions: [
      "هل يمكنني تجميد الاشتراك مؤقتًا؟",
      "ما هي الخدمات المشمولة في الاشتراك؟",
      "هل يمكن نقل الاشتراك لشخص آخر؟",
      "ما هو إجراء الإلغاء خطوة بخطوة؟",
    ],
  },
  rental_agreement: {
    contractType: "rental_agreement",
    title: "عقد إيجار شقة سكنية",
    summary: "عقد إيجار لشقة سكنية لمدة سنة كاملة بإيجار شهري ثابت.",
    parties: [{ name: "المستأجر", role: "tenant" }, { name: "المالك", role: "landlord" }],
    startDate: "2026-09-01",
    endDate: "2027-08-31",
    duration: "12 شهرًا",
    totalCost: 36000,
    currency: "SAR",
    monthlyPayment: 3000,
    deposit: 6000,
    automaticRenewal: false,
    cancellationAllowed: true,
    cancellationNoticeDays: 60,
    earlyCancellationPenalty: 3000,
    refundPolicy: "يُستردّ التأمين بعد إخلاء الوحدة وتفتيشها خلال 30 يومًا",
    clarityScore: 75,
    clarityExplanation: "العقد واضح بشكل عام مع بعض الغموض في شروط صيانة الممتلكات.",
    confidence: 0.88,
    clauses: [
      { category: "payment", title: "موعد دفع الإيجار", simpleExplanation: "يجب دفع الإيجار في بداية كل شهر.", riskLevel: "low", sourcePage: 2 },
      { category: "cancellation", title: "إشعار الإخلاء", simpleExplanation: "يجب إشعار المالك قبل 60 يومًا من الإخلاء.", riskLevel: "medium", sourcePage: 5 },
      { category: "maintenance", title: "مسؤولية الصيانة", simpleExplanation: "المستأجر مسؤول عن الأضرار الناتجة عن الإهمال.", riskLevel: "medium", sourcePage: 7 },
      { category: "deposit", title: "شروط استرداد التأمين", simpleExplanation: "يُستردّ التأمين خلال 30 يومًا بعد الإخلاء إذا لم تكن هناك أضرار.", riskLevel: "low", sourcePage: 3 },
    ],
    financialDetails: [
      { type: "monthly_payment", amount: 3000, currency: "SAR", description: "الإيجار الشهري" },
      { type: "deposit", amount: 6000, currency: "SAR", description: "مبلغ التأمين" },
      { type: "cancellation_penalty", amount: 3000, currency: "SAR", description: "غرامة الإخلاء المبكر" },
    ],
    contractDates: [
      { type: "start", date: "2026-09-01", description: "تاريخ بداية الإيجار" },
      { type: "end", date: "2027-08-31", description: "تاريخ انتهاء العقد" },
    ],
    suggestedQuestions: [
      "هل يمكن تعديل الإيجار خلال فترة العقد؟",
      "من المسؤول عن صيانة الأجهزة المنزلية؟",
      "هل يمكن تأجير الشقة من الباطن؟",
    ],
  },
  employment_contract: {
    contractType: "employment_contract",
    title: "عقد عمل في شركة تقنية",
    summary: "عقد عمل دائم بمرتب شهري ومزايا وظيفية.",
    parties: [{ name: "الموظف", role: "employee" }, { name: "شركة التقنية", role: "employer" }],
    startDate: "2026-10-01",
    duration: "غير محدد المدة",
    totalCost: null,
    currency: "SAR",
    monthlyPayment: 12000,
    automaticRenewal: false,
    cancellationAllowed: true,
    cancellationNoticeDays: 30,
    earlyCancellationPenalty: null,
    clarityScore: 82,
    clarityExplanation: "العقد واضح ومنظم بشكل جيد مع تفاصيل كافية.",
    confidence: 0.93,
    clauses: [
      { category: "non_compete", title: "بند عدم المنافسة", simpleExplanation: "لا يمكن العمل في شركات منافسة لمدة سنة بعد انتهاء العقد.", riskLevel: "high", sourcePage: 9 },
      { category: "probation", title: "فترة التجربة", simpleExplanation: "فترة تجربة 90 يومًا يمكن خلالها إنهاء العقد بدون تعويض.", riskLevel: "medium", sourcePage: 2 },
      { category: "overtime", title: "العمل الإضافي", simpleExplanation: "ساعات العمل الإضافية تُحسب بمعدل 1.5 ضعف الراتب.", riskLevel: "low", sourcePage: 4 },
    ],
    financialDetails: [
      { type: "monthly_payment", amount: 12000, currency: "SAR", description: "الراتب الشهري الأساسي" },
      { type: "bonus", amount: 24000, currency: "SAR", description: "مكافأة سنوية مشروطة بالأداء" },
    ],
    contractDates: [
      { type: "start", date: "2026-10-01", description: "تاريخ بداية العمل" },
      { type: "probation_end", date: "2026-12-30", description: "نهاية فترة التجربة" },
    ],
    suggestedQuestions: [
      "ما هي شروط الزيادة السنوية في الراتب؟",
      "هل يشمل العقد تأمينًا صحيًا للأسرة؟",
      "ما هي إجراءات إنهاء العقد من قِبل الشركة؟",
    ],
  },
};

export function getDemoAnalysis(contractType: string): object {
  return DEMO_ANALYSES[contractType] ?? DEMO_ANALYSES.gym_membership;
}
